### PR TITLE
Add support for VS Code as a Reporter

### PR DESCRIPTION
**Pull request by bzuillsmith**
VS Code is a very common editor these days, and is cross-platform. Would be nice to have this reporter available, maybe even by default. This is my stab at adding it. I haven't tested it on Mac or Linux yet. Works fine for me on windows.

### CODE REVIEW

**Comment by staxmanade** [comment]
Thanks for the contribution:

`npm run test` gives some errors

```
   9:1  error  Trailing spaces not allowed      no-trailing-spaces
  12:3  error  Expected { after 'if' condition  curly
  14:3  error  Expected { after 'else'          curly
```

Happy to merge once tests all good.

**Comment by staxmanade** [comment]
Just ran a local test and it popped up VSCode on my Mac. So, cool 👍

**Comment by bzuillsmith** [comment]
Ah, I didn't realize there was a linter because there were a couple tests not passing on my end before I even got started. Probably an environment issues? Or maybe related to updated dependencies?

- **Readme Should not allow the readme docs to get out of sync** -- something is up with `<code>` tags being a little out of place.
- **Reporter vimdiff reporter args are correct** -- `TypeError: Cannot read property 'replace' of null (at test\Reporting\Reporters\VimDiffReporterTests.js:18:12)`

**Comment by bzuillsmith** [comment]
Fixed the lint errors. Also, at first glance, that vimdiff reporter error seems to be because I don't have that utility on my system and the test relies on it being there.

The other error is giving me a diff for the readme like:

Received

`**Kind**: static property of [<code>approvals</code>](#module_approvals)`

Approved

`**Kind**: static property of <code>[approvals](#module_approvals)</code>`

It does that for all similar lines starting with `**Kind**`

**Comment by staxmanade** [comment]
The readme test failing is strange - the tests pass on my mac (after your linting update).

Thank you for the contribution!

For now we can ignore the readme error (unless you want to take time to figure it out. (guessing a difference between windows and mac?)

**Pull request merged**
