### PR TITLE
Changed reporters to be lazily loaded

### LINKED ISSUE #20: Slow performance on Windows
Hi,

Great project! Really glad to see that approvals has been ported to JavaScript (I use it extensively via .NET).

I'm not sure on what the performance expectations are for this project on Windows and I'm a little surprised with how long it seems to take to do an approval.

For instance, I just ran the following on a number of computers we have here:

```js
var approvals = require('approvals');

console.log (new Date().getTime() + " Starting");
try {
    approvals.verify(__dirname, "test", "asdf");
} catch (e) {
    console.log (e);
}
console.log (new Date().getTime() + " Finishing");
```

And it's taking between 1s - 3s depending on the machine and the diff viewer (e.g. kdiff, tortoisediff, p4merge, git diff). e.g.:

```
C:\dev\temp\> node main.js
1429163375410 Starting
CMD: C:/Program Files/TortoiseGit/bin/TortoiseGitMerge.exe C:\dev\temp\test.
received.txt C:\dev\temp\test.approved.txt
File sizes do not match:
Approved: C:\dev\temp\test.approved.txt
Received: C:\dev\temp\test.received.txt

1429163377028 Finishing
```

Is this expected? Is there anything I can do to improve performance? Is there any more information I can send you to help diagnose?

Thanks!

### PR DESCRIPTION
**Pull request by robdmoore**
Fixes #20 and results in a massive performance improvement in Windows

### CODE REVIEW

**Comment by robdmoore** [comment]
I tried this out on my project and it worked great! Huge performance improvement.

If you have a bunch of failures then they will still be slow, but I figure that's the rarer case and could still be addressed in the future. This fixes my immediate problems.

**Comment by robdmoore** [comment]
Also, FYI the two approval files in the test project fail on Windows due to line endings differences. Might be worth storing them as binary via gitattributes.

**Comment by staxmanade** [comment]
Thanks! Clean!

**Comment by robdmoore** [comment]
Thanks for the merge!

When do you think this might hit npm?

**Comment by staxmanade** [comment]
Let me know how this version looks.... [`0.0.27`](https://www.npmjs.com/package/approvals)

**Comment by robdmoore** [comment]
Works great! thanks so much! :)

**Pull request merged**
