### PR TITLE
Feature/fix issue 5

### PR DESCRIPTION
**Pull request by faceleg**

### CODE REVIEW

**Comment by staxmanade** [comment]
This looks amazing! - I'll have to check it out later... Thanks for the PR!

**Comment by faceleg** [comment]
:dancers:

**Comment by staxmanade** [comment]
I rebased it on a local commit I forgot I had - also removed one more usage of `mocha(__dirname)` in a test file.

Thanks for the change!

**Comment by faceleg** [comment]
No problem :)

**Pull request closed without merging**
