### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by staxmanade**

### CODE REVIEW

**Comment by cmstead** [comment]
Hooray!

**Comment by staxmanade** [comment]
@cmstead I'm just waiting for all the tests to pass... then I'll cut you release

**Comment by cmstead** [comment]
No worries. I just feel like open source peeps need to feel the love more. To that end, I thank you, sir!

**Comment by staxmanade** [comment]
@cmstead checkout `approvals@2.1.2` from npm and hopefully that works for you.

**Comment by cmstead** [comment]
I'll pull it and give it a go. Thanks for doing this! I appreciate it and I'm sure my coworkers will too. You're awesome.

**Pull request merged**
